from pathlib import Path

from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


OUTPUT_PATH = Path("reports") / "low_cost_deployment_architecture_and_pricing.xlsx"


def style_header(row):
    fill = PatternFill("solid", fgColor="001844")
    font = Font(color="FFFFFF", bold=True)
    for cell in row:
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(wrap_text=True, vertical="center")


def style_table_header(row):
    fill = PatternFill("solid", fgColor="D9EAF7")
    font = Font(color="001844", bold=True)
    for cell in row:
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(wrap_text=True, vertical="center")


def autosize(sheet):
    for column_cells in sheet.columns:
        width = 10
        for cell in column_cells:
            if cell.value is not None:
                width = max(width, min(len(str(cell.value)) + 2, 52))
        sheet.column_dimensions[get_column_letter(column_cells[0].column)].width = width


def apply_grid(sheet):
    thin = Side(style="thin", color="D9E2EC")
    border = Border(top=thin, left=thin, right=thin, bottom=thin)
    for row in sheet.iter_rows():
        for cell in row:
            cell.border = border
            cell.alignment = Alignment(wrap_text=True, vertical="top")


def title(sheet, text, end_col="F"):
    sheet["A1"] = text
    sheet["A1"].font = Font(size=16, bold=True, color="FFFFFF")
    sheet["A1"].fill = PatternFill("solid", fgColor="001844")
    sheet.merge_cells(f"A1:{end_col}1")


def build_workbook():
    wb = Workbook()
    summary = wb.active
    summary.title = "Executive Summary"
    architecture = wb.create_sheet("Architecture")
    assumptions = wb.create_sheet("Usage Assumptions")
    costs = wb.create_sheet("Monthly Cost Model")
    twilio = wb.create_sheet("Twilio Estimate")
    checklist = wb.create_sheet("Deployment Checklist")
    sources = wb.create_sheet("Sources")

    title(summary, "Low-Cost Deployment Cost Report", "F")
    summary.append([])
    summary.append(["Recommendation", "Use Render/Railway + SQLite on persistent disk + Twilio + Sentry free tier. Keep Postgres as a later upgrade."])
    summary.append(["Reason", "50 consultants and weekly usage create a small data volume, so SQLite is acceptable if the DB file is stored on persistent disk and backed up."])
    summary.append(["Estimated Monthly Cost - Low Reminder Usage", "='Monthly Cost Model'!D13"])
    summary.append(["Estimated Monthly Cost - Max Reminder Usage", "='Monthly Cost Model'!E13"])
    summary.append(["Expected One-Time Twilio Setup", "=SUM('Monthly Cost Model'!D16:D18)"])
    summary.append(["Production Caveat", "Do not store SQLite on ephemeral app storage. Use a persistent disk and backup hours.db regularly."])
    summary["A3"].font = Font(bold=True)
    summary["A4"].font = Font(bold=True)
    summary["A5"].font = Font(bold=True)
    summary["A6"].font = Font(bold=True)
    summary["A7"].font = Font(bold=True)
    summary["B5"].number_format = "$#,##0.00"
    summary["B6"].number_format = "$#,##0.00"
    summary["B7"].number_format = "$#,##0.00"

    title(architecture, "Minimal-Cost Architecture", "F")
    architecture.append([])
    architecture.append(["Layer", "Component", "Purpose", "Cost Impact"])
    rows = [
        ["Users", "50 consultants", "Reply to weekly SMS prompts and reminders", "No direct app cost"],
        ["Messaging", "Twilio A2P 10DLC", "Send prompts/reminders and receive replies at /sms", "Usage based"],
        ["Hosting", "Render paid web service or Railway", "Runs Flask dashboard/API", "~$7+/mo"],
        ["Database", "SQLite on persistent disk", "Stores consultants, responses, message logs, settings", "Very low disk cost"],
        ["Reports", "Weekly CSV + Monthly CSV/XLSX", "Generated by Flask app from SQLite data", "Included in app hosting"],
        ["Monitoring", "Sentry free tier", "Capture production errors", "$0 initially"],
        ["Local Testing", "ngrok", "Expose localhost to Twilio while testing", "$0 for basic dev use"],
    ]
    for row in rows:
        architecture.append(row)
    style_table_header(architecture[3])

    title(assumptions, "Usage Assumptions", "F")
    assumptions.append([])
    assumptions.append(["Input", "Value", "Notes"])
    assumption_rows = [
        ["Consultants", 50, "Current expected consultant count"],
        ["Weeks per month", 4.33, "Average calendar weeks per month"],
        ["Weekly prompt per consultant", 1, "One outbound weekly ask"],
        ["Reply per consultant per week", 1, "One inbound SMS reply"],
        ["Max daily reminders", 50, "Worst case: every consultant gets one reminder per day"],
        ["Days per month for reminders", 30, "Upper bound"],
        ["Weekly Excel/CSV reports", 4, "Generated by app, no SMS cost"],
        ["Database", "SQLite", "Keep until production needs require Postgres"],
    ]
    for row in assumption_rows:
        assumptions.append(row)
    style_table_header(assumptions[3])

    title(costs, "Monthly Cost Model", "F")
    costs.append([])
    costs.append(["Component", "Basis", "Notes", "Low Usage", "Max Reminder Usage"])
    monthly_rows = [
        ["Render web service", "Starter paid service", "Avoid free-tier sleep for production", 7.00, 7.00],
        ["Persistent disk", "Approx. 1 GB", "Stores SQLite hours.db and generated reports", 0.25, 0.25],
        ["Sentry", "Free tier", "Enough initially", 0.00, 0.00],
        ["ngrok", "Local testing only", "Not used in production", 0.00, 0.00],
        ["Twilio phone number", "One local long-code number", "Approximate", 1.15, 1.15],
        ["A2P campaign monthly fee", "Low-volume/sole-prop range", "Depends on registration type/use case", 2.00, 10.00],
        ["SMS base usage", "See Twilio Estimate", "Twilio segment cost estimate", "=Twilio Estimate!B10", "=Twilio Estimate!C10"],
        ["Carrier fees", "See Twilio Estimate", "Estimated blended carrier fees", "=Twilio Estimate!B11", "=Twilio Estimate!C11"],
    ]
    for row in monthly_rows:
        costs.append(row)
    costs.append([])
    costs.append(["Estimated Monthly Total", "", "", "=SUM(D4:D11)", "=SUM(E4:E11)"])
    costs.append([])
    costs.append(["One-Time Item", "Basis", "Notes", "Estimated Cost", "Optional/Range"])
    one_time_rows = [
        ["A2P brand registration", "Twilio", "Approximate", 4.50, ""],
        ["A2P campaign verification", "Twilio", "Manual vetting", 15.00, ""],
        ["Secondary vetting", "Twilio", "Only if required", 0.00, "Possible ~$41.50"],
    ]
    for row in one_time_rows:
        costs.append(row)
    style_table_header(costs[3])
    style_table_header(costs[15])
    for row in costs.iter_rows(min_row=4, min_col=4, max_col=5):
        for cell in row:
            cell.number_format = "$#,##0.00"

    title(twilio, "Twilio SMS Usage Estimate", "F")
    twilio.append([])
    twilio.append(["Metric", "Low Usage", "Max Reminder Usage", "Formula/Notes"])
    twilio_rows = [
        ["Weekly prompts/month", "=50*4.33", "=50*4.33", "50 consultants x 4.33 weeks"],
        ["Replies/month", "=50*4.33", "=50*4.33", "One reply per consultant per week"],
        ["Reminders/month", "=50*4.33*0.1", "=50*30", "Low assumes 10% reminder rate; max assumes daily reminders to all"],
        ["Total SMS segments", "=SUM(B4:B6)", "=SUM(C4:C6)", "Assumes one SMS segment per message"],
        ["Twilio base SMS rate", 0.0083, 0.0083, "Approx. per inbound/outbound SMS segment"],
        ["Estimated carrier fee", 0.0035, 0.0045, "Blended estimate; varies by carrier"],
        ["Base SMS cost", "=B7*B8", "=C7*C8", "Twilio base SMS cost"],
        ["Carrier fee estimate", "=B7*B9", "=C7*C9", "Estimated carrier pass-through fees"],
        ["Total SMS + carrier", "=B10+B11", "=C10+C11", "Before phone number and A2P monthly fees"],
    ]
    for row in twilio_rows:
        twilio.append(row)
    style_table_header(twilio[3])
    for row in twilio.iter_rows(min_row=8, min_col=2, max_col=3):
        for cell in row:
            cell.number_format = "$#,##0.0000"
    for row in twilio.iter_rows(min_row=10, min_col=2, max_col=3):
        for cell in row:
            cell.number_format = "$#,##0.00"

    chart = BarChart()
    chart.title = "Estimated Monthly Cost"
    chart.y_axis.title = "USD"
    chart.x_axis.title = "Scenario"
    chart_data_start = 17
    twilio.cell(row=chart_data_start, column=1, value="Scenario")
    twilio.cell(row=chart_data_start, column=2, value="Estimated Monthly Total")
    twilio.cell(row=chart_data_start + 1, column=1, value="Low Usage")
    twilio.cell(row=chart_data_start + 1, column=2, value="='Monthly Cost Model'!D13")
    twilio.cell(row=chart_data_start + 2, column=1, value="Max Reminder Usage")
    twilio.cell(row=chart_data_start + 2, column=2, value="='Monthly Cost Model'!E13")
    chart.add_data(Reference(twilio, min_col=2, min_row=chart_data_start, max_row=chart_data_start + 2), titles_from_data=True)
    chart.set_categories(Reference(twilio, min_col=1, min_row=chart_data_start + 1, max_row=chart_data_start + 2))
    chart.height = 8
    chart.width = 14
    twilio.add_chart(chart, "F3")

    title(checklist, "Deployment Checklist", "F")
    checklist.append([])
    checklist.append(["Step", "Owner", "Status", "Notes"])
    checklist_rows = [
        ["Choose host: Render or Railway", "Team", "Pending", "Lowest-cost path can use Render web service + disk"],
        ["Attach persistent disk", "Developer", "Pending", "Required for SQLite durability"],
        ["Set DB_PATH to disk mount", "Developer", "Pending", "Example: /var/data/hours.db"],
        ["Set ADMIN_PASSWORD", "Developer", "Pending", "Protect dashboard/API"],
        ["Register Twilio A2P campaign", "Business/Admin", "Pending", "Required for US production SMS"],
        ["Set PUBLIC_BASE_URL", "Developer", "Pending", "Needed for Twilio webhook validation"],
        ["Point Twilio webhook to /sms", "Developer", "Pending", "https://your-domain.com/sms"],
        ["Configure Sentry DSN", "Developer", "Optional", "Free tier initially"],
        ["Set backup process for hours.db", "Developer", "Pending", "Download/copy daily or use disk snapshots"],
        ["Run production smoke test", "Team", "Pending", "SMS reply, dashboard, weekly CSV, monthly CSV/XLSX"],
    ]
    for row in checklist_rows:
        checklist.append(row)
    style_table_header(checklist[3])

    title(sources, "Sources and Pricing References", "F")
    sources.append([])
    sources.append(["Topic", "URL", "Notes"])
    source_rows = [
        ["Twilio SMS pricing", "https://www.twilio.com/en-us/sms/pricing/us", "SMS segment pricing and carrier fee references"],
        ["Twilio A2P 10DLC overview", "https://www.twilio.com/en-us/phone-numbers/a2p-10dlc", "Brand/campaign registration and monthly campaign fee range"],
        ["Twilio A2P vetting FAQ", "https://help.twilio.com/articles/11587910480155", "Campaign verification fee and approval timeline"],
        ["Render pricing", "https://render.com/pricing", "Hosting pricing reference"],
        ["Render persistent disks", "https://render-web.onrender.com/docs/disks", "Persistent disk behavior and snapshots"],
        ["ngrok pricing", "https://ngrok.com/pricing", "Local development tunnel pricing"],
    ]
    for row in source_rows:
        sources.append(row)
    style_table_header(sources[3])
    for row in sources.iter_rows(min_row=4, min_col=2, max_col=2):
        for cell in row:
            cell.hyperlink = cell.value
            cell.style = "Hyperlink"

    for sheet in wb.worksheets:
        sheet.freeze_panes = "A4"
        apply_grid(sheet)
        autosize(sheet)
        sheet.sheet_view.showGridLines = False

    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    wb.save(OUTPUT_PATH)
    return OUTPUT_PATH


if __name__ == "__main__":
    print(build_workbook())
